#pragma once

enum ANGLE {ANGLE_X, ANGLE_Y, ANGLE_Z, ANGLE_END};

enum RENDERGROUP { TYPE_PRIORITY, TYPE_NONEALPHA, TYPE_ALPHA, TYPE_UI, TYPE_END };

enum RESOURCETYPE { RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_STATIC, RESOURCE_END };

enum BUFFERTYPE { BUFFER_RCCOL,BUFFER_RCTEX, BUFFER_TERRAIN, BUFFER_CUBETEX, BUFFER_CUBECOL };

enum TEXTURETYPE { TEXTURE_NORMAL, TEXTURE_CUBE };

enum ShaderType {SHADER_VS, SHADER_PS, SHADER_ANI, SHADER_DS, SHADER_HS, SHADER_GS, SHADER_LINE_VS, SHADER_SHADOW_VS, SHADER_END};

enum ReleaseType {Release_Static, Release_Dynamic, Release_End};

enum Scene_Tyep {SCENE_LOGO, SCENE_STAGE, SCENE_END};

enum DrawType { DRAW_INDEX, DRAW_VERTEX, DRAW_LINE };

enum MESHTYPE{ MESH_STATIC, MESH_DYNAMIC };

enum FontType{ FONT_TYPE_BASIC, FONT_TYPE_OUTLINE };

enum PLAYER_STATE{ PLAYER_IDLE, PLAYER_MOVE, PLAYER_ATT1, PLAYER_ATT2, PLAYER_ATT3, PLAYER_SKILL1, PLAYER_SKILL2, PLAYER_DEAD};

enum MONSTER_STATE{ MONSTER_IDLE, MONSTER_MOVE, MONSTER_ATT, MONSTER_KNOCK, MONSTER_DEAD};

enum BOSS_STATE{BOSS_IDLE, BOSS_MOVE, BOSS_ATT1_1, BOSS_ATT1_2, BOSS_ATT1_3, BOSS_ATT2, BOSS_ATT3, BOSS_BUFF, BOSS_GEN, BOSS_DEAD};

enum CELLTYPE { TYPE_TERRAIN, TYPE_CELL, TYPE_MESH };

enum CHATKEY { CHAT_SPACE = 32, CHAT_ENTER = 13, CHAT_BACKSPACE = 8};