#pragma once

enum ANGLE {ANGLE_X, ANGLE_Y, ANGLE_Z, ANGLE_END};
enum REDNERGROUP { TYPE_PRIORITY, TYPE_NONEALPHA, TYPE_ALPHA, TYPE_UI, TYPE_END };
enum RESOURCETYPE { RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_STATIC, RESOURCE_END };
enum BUFFERTYPE { BUFFER_RCCOL,BUFFER_RCTEX, BUFFER_TERRAIN, BUFFER_CUBETEX, BUFFER_CUBECOL,BUFFER_CYLINDER };
enum ShaderType {SHADER_VS, SHADER_PS, SHADER_END};
enum TEXTURETYPE {TEXTURE_NORMAL, TEXTURE_CUBE};